export const PUBLIC_API_ACTIONS = new Set(['login', 'portalLogin', 'portalData'])

export const PRIVATE_API_ACTIONS = new Set([
  'getDashboardHoy',
  'getQuincena',
  'getQuincenaAnterior',
  'getComparativa',
  'exportarDatos',
  'getCargasPorProveedor',
  'getCargas',
  'getCargasPorRango',
  'getMedicionesPorRango',
  'saveCarga',
  'editarCarga',
  'deleteCarga',
  'getMedicion',
  'saveMedicion',
  'editarMedicion',
  'deleteMedicion',
  'getProveedores',
  'saveProveedor',
  'toggleProveedor',
  'deleteProveedor',
  'getProveedorPorCodigo',
  'getUsuarios',
  'saveUsuario',
  'toggleUsuario',
  'deleteUsuario',
  'subirFoto',
  'getCompradores',
  'saveComprador',
  'toggleComprador',
  'getPrecioComprador',
  'savePrecioComprador',
  'getPreciosHistorial',
  'saveEnvio',
  'getEnviosPorFecha',
  'getEnviosPorRango',
  'editarEnvio',
  'saveRemanente',
  'getRemanentePendiente',
  'usarRemanente',
  'ignorarRemanente',
  'getResumenFinancieroDia',
  'getDashboardFinanciero',
  'getTarifaProveedor',
  'getAllTarifas',
  'saveTarifa',
  'generarPlanilla',
  'generarTodasLasPlanillas',
  'marcarPlanillaPagada',
  'calcularPeriodoProveedor',
  'getPlanillasQuincena',
  'getPlanillasPorProveedor',
  'getComparativaProveedores',
  'getCategorias',
  'saveCategoria',
  'toggleCategoria',
  'saveGasto',
  'getGastosPorFecha',
  'getGastosPorRango',
  'editarGasto',
  'deleteGasto',
  'getAlertasConfig',
  'saveAlertaConfig',
  'toggleAlerta',
  'getAccesosProveedores',
  'generarAccesoProveedor',
])

export function isPublicApiAction(action: string): boolean {
  return PUBLIC_API_ACTIONS.has(action)
}

export function isAllowedApiAction(action: string): boolean {
  return isPublicApiAction(action) || PRIVATE_API_ACTIONS.has(action)
}
